version: '3.1'
services:
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=root
        volumes:
          - ./data/db:/data/db
        ports:
          - 27017:27017
        command: mongod --auth --logpath=/dev/null # --quiet
